"""partial unique constraint for booking

Revision ID: a1aab5530f13
Revises: a7ddadc200e5
Create Date: 2026-02-24 23:03:41.871782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1aab5530f13'
down_revision: Union[str, Sequence[str], None] = 'a7ddadc200e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_user_booking_per_slot'), 'bookings', type_='unique')
    op.create_index('unique_confirmed_booking', 'bookings', ['slot_id', 'telegram_user_id'], unique=True, postgresql_where=sa.text("status = 'CONFIRMED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_confirmed_booking', table_name='bookings', postgresql_where=sa.text("status = 'CONFIRMED'"))
    op.create_unique_constraint(op.f('unique_user_booking_per_slot'), 'bookings', ['slot_id', 'telegram_user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
